### ISSUE TITLE
Add typo autocorrect to editor.

### ISSUE THREAD

**Issue by anilgulecha** [oskusalerma/trelby#106]
Pidgin IM client has this nice addon that replaces wrongly typed words.

A pretty big list can be found at
http://en.wikipedia.org/wiki/Wikipedia:Lists_of_common_misspellings

So when you type teh or liek or isnt or didnt , Trelby automatically converts them to the, like, isn't and didn't as you type. 

When a user backspaces on an autocorrect, disable it for that line, and allow the user to type whatever.

**Comment by oskusalerma** [comment]
Closing, this is not going to happen.
