### ISSUE TITLE
Spell checker words and suggestion need improvement

### ISSUE THREAD

**Issue by anilgulecha** [oskusalerma/trelby#209]
I recently wrote ahrd, and hard was not suggested.

I did not find 'graphene' in the list. (it looks like firefox does not recognize it either). Perhaps it's time to update the list of words from a more modern dictionary.

We could simply outsource the dictionary work to any of the dictionary libraries already out there to implement this. This has the advantage of using dictionaries in many languages. The openoffice ones seem to be extensive, and have python libraries.

www.rfk.id.au/software/pyenchant/

---

Also,
```
$ diff /usr/share/dict/words  ~/projects/trelby/dict_en.dat | grep ^\< | wc -l
20278
```

So we can also simply update the word list too.

**Comment by oskusalerma** [comment]
Issue cleanup: doubt this will ever happen, so closing.
