### ISSUE TITLE
Auto-save/crash recovery

### ISSUE THREAD

**Issue by anilgulecha** [oskusalerma/trelby#245]
I was just bitten by some bug, which froze Trelby, and I lost about 3 pages of work. As rare as these are, I would hate to have this happen even one more time, and lose even a single page. So there's two types of autosave:

* Autosave every 'x' minutes, so I don't have to manually "ctrl+s" as I type.

This is implemented with a simple timer, and a config option in global settings. Default x to 2. This option is off by default.

* Save my open scripts into a temporary directory (trelby config directory) and when the program exists cleanly, delete these files. After a unclean exit, recover files.

This feature is also selected via global config, and is turned on by default. This is implemented by saving open files every 2 or 1 minute (unconfigurable - we select a low default), and when the timer fires we a) save all the files to .trelby/auto directory. On exit, we clear this directory. On startup, we check if there are any files in here, and if yes, present the user with a message box "These were autosaved, and available for recovery", and let him open these files.

@oskusalerma Thoughts?

**Comment by oskusalerma** [comment]
Issue cleanup: doubt this will ever happen, so closing.
