### ISSUE TITLE
Improve and modernize spellchecker 

### ISSUE THREAD

**Issue by anilgulecha** [oskusalerma/trelby#3]
Currently the built in spellchecker is a dialog of it's own, following the tradition of very early MS office workflow.

This needs to be updated to Firefox like spell-checking.
 - tiny red underline below unidentified words as they are typed (real-time spellchecking)
 - right clicking on the word provides options:
   > Add to dictionary
   > Spelling suggestions

The real-time spellchecking can be turned on or off via the Tools menu.

**Comment by ElecProg** [comment]
If there would be some sort of spellchecking for multiple languages, I think it would be helpful if the language setting was saved in configuration part of the file.

**Comment by oskusalerma** [comment]
As per the discussion on the mailing list, it is confusing to everyone to have this issue open when we are never going to have the resources to work on the spellchecking code, so I am closing this.

**Comment by HuBandiT** [comment]
@anilgulecha Word lists will not work for strongly agglutinating and compounding languages. The best example I know for this is Hungarian - the very reason for existence of Hunspell - where exhaustively listing all possible word forms would reach on the order of several millions or even a (US) billion (10^9). If you want to do spell checking properly nowadays that is not limited in the set of languages possible, you should consider to use Hunspell. You will also benefit from the countless man-hours continuously put in by the community into maintaining the dictionaries for many languages.
