### ISSUE TITLE
Characters script like Locations script

### ISSUE THREAD

**Issue by ghzakaria** [oskusalerma/trelby#328]
The locations script (the one that joins multiple locations into one) is really smart.
Characters need a script too, so the program understands: CHARACTER NAME, CHARACTER NAME (CONT'D), CHARACTER NAME (O.S.), CHARACTER NAME (V.O.), etc. as one character.

**Comment by oskusalerma** [comment]
Issue cleanup: doubt this will ever happen, so closing.
