### ISSUE TITLE
please update for python-wxgtk3.0

### ISSUE THREAD

**Issue by onlyjob** [oskusalerma/trelby#354]
Please update for WX-3.0 in order to decommission obsolete WX-2.8.

Besides on Debian `trelby` is not even starting when both _python-wxgtk2.8_ and _python-wxgtk3.0_ are installed:

~~~~
You seem to have an invalid version
(3.0.1.1) of wxWidgets installed. This
program needs version 2.8.
~~~~

Probably to fix it "python-wxversion" can be of help in short term until migration is finished.
The following is a quote from _wxversion.py_:

~~~~
If you have more than one version of wxPython installed this module
allows your application to choose which version of wxPython will be
imported when it does 'import wx'.  The main function of this module
is `select` and you use it like this::

    import wxversion
    wxversion.select('2.4')
    import wx

Or additional build options can also be selected, although they will
not be required if they are not installed, like this::

    import wxversion
    wxversion.select('2.5.3-unicode')
    import wx

Or you can require an exact match on the build options like this::

    import wxversion
    wxversion.select('2.5.3-unicode', optionsRequired=True)
    import wx

Finally you can also specify a collection of versions that are allowed
by your application, like this::

    import wxversion
    wxversion.select(['2.5.4', '2.5.5', '2.6'])
    import wx


Of course the default wxPython version can also be controlled by
setting PYTHONPATH or by editing the wx.pth path configuration file,
but using wxversion will allow an application to manage the version
selection itself rather than depend on the user to setup the
environment correctly.

It works by searching the sys.path for directories matching wx-* and
then comparing them to what was passed to the select function.  If a
match is found then that path is inserted into sys.path.

NOTE: If you are making a 'bundle' of your application with a tool
like py2exe then you should *not* use the wxversion module since it
looks at the filesystem for the directories on sys.path, it will fail
in a bundled environment.  Instead you should simply ensure that the
version of wxPython that you want is found by default on the sys.path
when making the bundled version by setting PYTHONPATH.  Then that
version will be included in your bundle and your app will work as
expected.  Py2exe and the others usually have a way to tell at runtime
if they are running from a bundle or running raw, so you can check
that and only use wxversion if needed.  For example, for py2exe::

    if not hasattr(sys, 'frozen'):
        import wxversion
        wxversion.select('2.5')
    import wx

More documentation on wxversion and multi-version installs can be
found at: http://wiki.wxpython.org/index.cgi/MultiVersionInstalls
~~~~

**Comment by woodape** [comment]
Until this is fixed, Trelby will be unusable on the-soon-to-be-stable Debian Jessie which only supports WX-3.0.

**Comment by oskusalerma** [comment]
Will probably look at this when I upgrade to Jessie after it's released.

**Comment by onlyjob** [comment]
Why wait? IMHO it would make sense to fix before Jessie so those who upgrade would not lose ability to run _trelby_. Besides this problem blocks _trelby_ packaging for Debian...

**Comment by oskusalerma** [comment]
Because I can't develop the fix until I'm running Jessie, which I won't be
until Jessie is released.

**Comment by onlyjob** [comment]
Well at least I hope it won't be long because Jessie is in the late stage of pre-release freeze.

**Comment by woodape** [comment]
You can always grab a Debian Jessie ISO [here](https://www.debian.org/devel/debian-installer/) and install it on a virtual machine. This version was last updated 27 Mar 2015, so it is as close to the release candidate as one will get. Besides, though the issue certainly exists for a fresh install of Debian 8, the issue may not exist (not sure) for machines upgraded from Debian 7 to Debian 8, as Debian 7 supports WX-2.8, thus testing for breakage on an upgraded machine may not be correct.

**Comment by oskusalerma** [comment]
There's a lot of things I could do with infinite time available to me. As
it is, I only have very limited time available to spend on Trelby, so I
have to optimize that time as well as possible.

There are 7 billion people on the planet. Any one of them is free to send
me patches fixing this problem. Holding me to a higher standard than
literally everyone else on the planet, after I've already done more for
free screenwriting software than, again, literally everyone else on the
planet, is not reasonable.

**Comment by onlyjob** [comment]
There may be no glory in your hard work and little appreciation.
But if you care to fix this problem I will help you to include trelby into 
Debian. This will give you greater exposure which will eventually attract
new contributors.

---

Good luck happens when preparedness meets opportunity.

**Comment by oskusalerma** [comment]
That seems very unlikely.

**Comment by onlyjob** [comment]
May be. But you need to make contributions welcome. Merging pull requests help. ;)
You could be discouraged from working on trelby right now but hopefully this bug is easy enough to fix. In Debian one person transitioned (or helped to transition) dozens of packages to WX-3.0. (Many of those packages he did not use). That is one of the way of contribution to work. You can check bug tracker for details.
I'm sure you'll fix this bug eventually if trelby worth it...

**Comment by oskusalerma** [comment]
As I said, I'll fix it once Jessie is released and I've personally switched
over to it. Or when somebody sends a pull request fixing it before, and it
looks good enough to include without me personally being able to test it.

**Comment by onlyjob** [comment]
[Debian 8 "Jessie" released](https://www.debian.org/News/2015/20150426)

**Comment by oskusalerma** [comment]
OK, I'll eventually upgrade to it and fix whatever needs fixing in trelby
to make it work again.

**Comment by onlyjob** [comment]
Thank you. I'm looking forward to test. :)

**Comment by 4thguy** [comment]
Tentative workaround until the wxWidgets 3.0 replaces 2.8
https://github.com/oskusalerma/trelby/pull/364

**Comment by gazhay** [comment]
As OP indicates, Trelby will function fine if you patch the trelby.py file.

Add 
     import wxversion
     wxversion.select('2.8')
    
near the top of the file.

**Comment by yutzhead** [comment]
Doesn't help on Fedora 22 as there is no wxPython 2.8 anymore.

**Comment by oskusalerma** [comment]
I've ugpraded to Jessie finally. Will now fix Trelby to work with wxPython 3.0.

**Comment by onlyjob** [comment]
Thank you for update. I believe this qualifies for new release (i.e. version bump).
Also we need new version if we are going to proceed with packaging for inclusion to Debian...

**Comment by danielhjames** [comment]
Hi, I am not an official Debian Developer but I do maintain a sponsored package in Debian. I would recommend that the project addresses any issues that would prevent inclusion in Debian before making a release for that purpose. That's because if any issues were found, another release would be required. So I'd recommend running lintian -i --pedantic on the .changes file of your test package first.

Also I would recommend moving the debian directory to a separate repo, such as https://github.com/oskusalerma/trelby-packaging as this separation is preferred by Debian nowadays. It also enables pull requests against packaging files without touching the program source.

**Comment by onlyjob** [comment]
I would have introduced Trelby to Debian long time ago if only Trelby were better maintained...

**Comment by oskusalerma** [comment]
Doubt Trelby will ever be included in Debian. We certainly don't have any
manpower available to do any work on that.

**Comment by danielhjames** [comment]
There are two aspects, the packaging work (which I would be happy to help with), and any upstream tweaks required to bring the released code into line with Debian's standards (which really needs developers with upstream knowledge to assist).

An example of the latter aspect would be moving fonts out of the install tarball if Debian already ships those fonts in their own package. This kind of change can sometimes be done by a release script rather than by modifying the upstream git sources.

**Comment by onlyjob** [comment]
We can take care of Debian packaging but software should be maintained in order to be accepted...

**Comment by danielhjames** [comment]
In the best case, the upstream developer would respond to bugs filed against the package, but Debian can patch its own version if necessary. If no-one comes forward to do that, the package is likely to be removed from Debian.

**Comment by tgirod** [comment]
I managed to install trelby on debian jessie by manually installing the following packages:

http://ftp.uk.debian.org/debian/pool/main/w/wxwidgets2.8/libwxgtk2.8-0_2.8.12.1-12_amd64.deb
http://ftp.uk.debian.org/debian/pool/main/w/wxwidgets2.8/python-wxgtk2.8_2.8.12.1-12_amd64.deb

The I installed trelby with dpkg, and added the following lines  at the begining of /opt/trelby/src/trelby.py 

```
import wxversion
wxversion.select('2.8')
```

It feels unclean, but when dev time is scarce, I guess someone has to get dirty ;)
