### ISSUE TITLE
Feature request: accept command line parameter

### ISSUE THREAD

**Issue by DaveJarvis** [oskusalerma/trelby#358]
# Replicate

Create a script (`$HOME/bin/trelby`) or an alias (`alias trelby=/opt/trelby/src/trelby.py`) to run:

```
#!/bin/bash
/opt/trelby/src/trelby.py "$@"
```

Then:

1. `cd $HOME/work/screenplays/shakespeare/`
1. `trelby macbeth.fountain`

# Expected Results

Trelby opens the file.

# Actual Results

Error loading file 'macbeth.fountain': No such file or directory

**Comment by oskusalerma** [comment]
Nothing to do with trelby. If it can't find the file, the script is interfering with the current directory, or something. It works fine if you pass in the complete filepath.
