### ISSUE TITLE
Feature request: merge open/import, save as/export

### ISSUE THREAD

**Issue by DaveJarvis** [oskusalerma/trelby#359]
# Replicate

1. Run Trelby
1. Select File >> Open

# Expected Results

Can open any type of screenplay file that Trelby supports.

# Actual Results

Only .trelby file extensions are possible to open.

# Work Around

Select File >> Import, instead.

# Additional Details

Trelby should use the filename extension to detect what type of file is being opened. While it is possible to drop FDX content into a file with a .fountain extension, I'd imagine such cases are exceptionally rare.

Simplify the UI and the UX by providing a single way to open any screenplay file.

Once Trelby doesn't have two different logic paths for opening files (i.e., open vs. import, but simply one path: open), then issue #360 becomes easier to implement.

**Comment by DaveJarvis** [comment]
Similarly, "Save As" and "Export" can be merged.

**Comment by oskusalerma** [comment]
But they are completely different code paths. All programs have a "save as" which saves files in native format which keeps all data, and "export" which exports to non-native formats in a data-losing way. Trelby follows this.
