### ISSUE TITLE
Feature request: command line options for file conversions

### ISSUE THREAD

**Issue by DaveJarvis** [oskusalerma/trelby#360]
# Replicate

Command line examples:

```
$ trelby macbeth.fountain -o macbeth.trelby
$ trelby macbeth.trelby -o macbeth.fdx
$ trelby macbeth.fdx -o macbeth.pdf
```
Using the `-o` parameter puts Trelby into "batch mode," which suppresses the GUI and terminates after conversion. Ideally, many Python API calls would be exposed through command-line options for fine-grained control. This would require a "--help" option.

# Expected Results

* Trelby runs headless
* Trelby converts the input file to the given output file, using the file name extension to detect format conversions
* Trelby terminates after conversion completes

# Actual Results

After running "trelby --help", Trelby tries to open a file called "--help".

**Comment by oskusalerma** [comment]
Trelby is not meant to be a batch processor, but an interactive screenplay writing program.
