### ISSUE TITLE
Feature request: reference variables in content text

### ISSUE THREAD

**Issue by DaveJarvis** [oskusalerma/trelby#361]
# Overview

Allow Trelby to use and substitute variables.

# Replicate

1. Create a file (e.g., `macbeth.yaml`) using [YAML format](http://en.wikipedia.org/wiki/YAML#Examples).
1. Allow user to associate the variable file with the screenplay file.
  - Implicitly by filename matching (e.g., "macbeth.trelby" uses "macbeth.yaml")
  - Explicitly through external configuration
1. Preprocess screenplay document using YAML variables, for example:

```
EXT. A DESERT PLACE - NIGHT

Thunder and lightning. Enter three $antagonist.vocation.plural$.

^antagonist.primary.name.first^
When shall we three meet again
In thunder, lightning, or in rain?

^antagonist.secondary.name.first^
When the hurlyburly's done,
When the battle's lost and won.

^protagonist.name.first^
Upon this blasted heath you stop our way
With such prophetic greeting? Speak, I charge you.

*The $antagonist.vocation.plural$ vanish.*
```

Eventually, having the UI provide the ability to auto-complete variable names would be incredibly handy (with preference ordering on most commonly used script variables).

In theory, [pandoc](http://johnmacfarlane.net/pandoc/) and some innovative shell scripting could accomplish the variable substitution, but not the UI auto-complete and selection. This isn't ideal, for a few reasons, including uppercasing.

In screenplays, uppercase names are quite common. While possible to brute force the issue using YAML by having a variable definition for the title case and the uppercase name, that introduces a bit of redundancy. To eliminate the redundancy, it'd be nice to have an alternate syntax wrapping the same variable:

```
---
protagonist:
  name:
    first: Macbeth
    last: MacFindlaech
antagonist:
  vocation:
    name: witch
    plural: witches
...
```

Then `$protagonist.name.first$` would substitute verbatim and `^protagonist.name.first^` would render the text in uppercase.

**Comment by oskusalerma** [comment]
Trelby is not a batch processor, but an interactive screenplay writing program.
