### ISSUE TITLE
A refresh feature for more seamless integration with git

### ISSUE THREAD

**Issue by kr0** [oskusalerma/trelby#362]
I use gitlab for my screen plays. Whenever I switch branches I have to close and reopen the current file in trelby to reflect the changes from switching branches.

The feature I imagine would refresh the view if the file changed or alternatively, just a refresh button.

**Comment by oskusalerma** [comment]
The downside of throwing away possible user changes is infinitely greater than the limited upside of your advanced usecase. We will not be implementing this.
