### ISSUE TITLE
Import Unicode text files

### ISSUE THREAD

**Issue by hellpe** [oskusalerma/trelby#368]
Currently, it seems that only ASCII text files can be imported to Trelby. I'm trying to import a file written in French, and Trelby replaces characters such as "é" with "Ã©", which requires spending a lot of time doing tiresome corrections.

**Comment by HuBandiT** [comment]
Is it anything better with my version discussed here?: https://github.com/oskusalerma/trelby/issues/85

**Comment by oskusalerma** [comment]
Imported text files must be Latin-1 encoded. Looks like you're trying to use UTF-8 encoded files; that's not supported.
