### ISSUE TITLE
Error: Wrong version of WxWidgets even though I have the correct one

### ISSUE THREAD

**Issue by gnaag** [oskusalerma/trelby#369]
When I start deb installed Trelby (from www.trelby.com), instead of opening the application there is an error dialog:

> You seem to have an invalid version (3.0.1.1) of wxWidgets installed. This program needs version 2.8.

However I have both versions of wxWidgets installed on my machine (Ubuntu 15.04) and I have python-wxversion installed as well (that is supposed to choose the right wxwidgets version for the application). In Terminal there is no data as for how the Trelby determines what version is installed on the system.

The packages of wx that I have in both versions:
- libwxbase2.8
- libwxbase3.0
- libwxgtk2.8
- libwxgtk3.0
- pythonwxgtk2.8
- pythonwxgtk3.0

Of libwxgtk-media2.8 there is only 2.8 version on my system.

**Comment by gnaag** [comment]
I have found a problem. Trelby is not calling wxversion at all. I have added this code
<pre>import wxversion
wxversion.select('2.8')</pre>

 at the beginning of /opt/trelby/src/trelby.py file and now it is working as expected. The beggining fo the file looks like this now:
<pre>#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-</pre>
<pre>
from error import *
import wxversion
wxversion.select('2.8')
import autocompletiondlg
import cfgdlg
import characterreport
import charmapdlg
import commandsdlg</pre>

**Comment by oskusalerma** [comment]
Yeah we probably should do that.

**Comment by danielhjames** [comment]
Hi, I experienced the opposite problem when installing from git master branch on Debian wheezy, Trelby complained that I had 2.8 but it wanted 3.0 :-)

![screenshot from 2015-12-04 14 39 12](https://cloud.githubusercontent.com/assets/1867708/11592652/d1e64200-9a97-11e5-9048-4ad989200005.png)

Trelby 2.2 from http://www.trelby.org/download runs fine on the same system.
