### ISSUE TITLE
better constant for approximating a (quarter) circle with a cubic Bézier curve - one-liner

### ISSUE THREAD

**Issue by HuBandiT** [oskusalerma/trelby#370]
[This article](http://spencermortensen.com/articles/bezier-circle/) suggests `0.551915024494` as the best constant to use for https://github.com/oskusalerma/trelby/blob/master/src/pdf.py#L130 .

**Comment by ElecProg** [comment]
I added a pull request implementing this feature.

**Comment by HuBandiT** [comment]
Thank you kindly, Sir. Please make sure you experimentally validated which direction the deviation of 0.05191... from 0.5 should be for the correct geometry. And including a link to the article detailing the math could be also educative for future generations.

**Comment by ElecProg** [comment]
![Comparison](https://cloud.githubusercontent.com/assets/5394549/11343370/1025455a-920c-11e5-9a1b-54641c4cccdf.png) Here is the difference the new clearly looks better than the old constant.
The commit standard of the project doesn't allow for any further change after a pull request is made, so I can't add a link to the article in the comments any more however, sources on the internet can change and sometimes disappear so adding a link, that may be gone in the future, maybe isn't a verry good idea anyway. But the difference (how much of a irrelevant detail it may seem to some) is clear the proposed constant is way better!

**Comment by oskusalerma** [comment]
Where did you get the idea of "The commit standard of the project doesn't allow for any further change after a pull request is made"? The change is fine, but I agree that the source of this new constant must be mentioned in the code; the comment you've changed would be a lie after your change.

**Comment by oskusalerma** [comment]
You need to withdraw your pull request, make needed changed, and resubmit.

**Comment by ElecProg** [comment]
OK I'll add a comment with the link and a short summary (should the source ever disappear) wheb I have some spare time in the comming week(s)
