### ISSUE TITLE
ALT code characters don’t work

### ISSUE THREAD

**Issue by SHARKvince** [oskusalerma/trelby#371]
On Windows, ALT code characters don’t work.
For example, if you enter alt+0146 (curly apostrophe: ’) in Trelby, it doesn’t get picked up.

**Comment by ElecProg** [comment]
It took some time to figure out for me but:
Trelby does support ALT codes (eg. try ALT+45), however it only supports Latin-1 (ISO/IEC 8859-1).
Curly apostrophe for example isn't part of Latin-1, so it's detected as an invalid character by the program and ignored.

Your problem is the same as #85
