### ISSUE TITLE
Use shift to select and ctrl+ arrow key

### ISSUE THREAD

**Issue by DMarm** [oskusalerma/trelby#374]
It would be good to have the shift key to select multiple characters.
I use it all the time, if you put your cursor to one character and then shift+click on an other it will select all the characters inbetween.

Plus using the ctrl+arrowkey combination allow to speed the cursor when selecting.
So ctrl+shift+arrow key allow you to select text faster than the standard behavior.

**Comment by oskusalerma** [comment]
ctrl+arrowkeys (up and down, anyway) already have a function assigned to them.
