### ISSUE TITLE
Version information needs to be updated in way too many places.

### ISSUE THREAD

**Issue by ElecProg** [oskusalerma/trelby#376]
Found this in the TODO list:
"-version information needs to be updated in way too many places. figure
 out a way to have it in as few places as possible so it's easier to
 update. currently it must be updated in:

  -misc.py
  -install.nsi
  -debian/changelog
  -doc/version.xml"

**Comment by ElecProg** [comment]
Ok so I think that the best solution would be to make a tool that updates the version numbers.
I got something for doc/version.xml and src/misc.py, who use 2.3-dev.
However, install.nsi uses 2.3.0.0-dev. Has this a reason or can it just be changed to 2.3-dev?

**Comment by anilgulecha** [comment]
I believe that's because the nsi format required that -- probably due to a
platform requirement.

**Comment by ElecProg** [comment]
Ok I'll take a look at the specifications.

**Comment by ElecProg** [comment]
Ok apparently it's a requirement of Windows to have a version number of the format X.X.X.X (which can't contain non integers btw. so the `-dev` in `2.3.0.0-dev` isn't supported).

**Comment by ElecProg** [comment]
Should there be made a difference between `-dev` non -dev versions in the `install.nsi` file?

**Comment by ElecProg** [comment]
Ok I'll guess not (since there have been no dev, alpha, beta, etc. releases.) Opening a pull request shortly.

**Comment by oskusalerma** [comment]
As discussed in your pull request.
