### ISSUE TITLE
Page break on new Act

### ISSUE THREAD

**Issue by aussiedoug** [oskusalerma/trelby#377]
I realise that this was discounted as item 103.  However maybe there is a simpler way to add this very desirable feature.  If the act object? had a property page break that need only affect pdf output.  I imagine that wouldn't be too hard or slow the system down or require lots of memory.  To avoid unnecessary page breaks the software would, presumably, only need to check its current print position.  Current workaround is to make each act separate file, generate and use pdftk to manipulate and combine.  Just my suggestion.  Thanksfor Trelby

**Comment by oskusalerma** [comment]
No, I don't think we're going to do this.
