### ISSUE TITLE
Support copy and paste from external sources

### ISSUE THREAD

**Issue by hesco** [oskusalerma/trelby#379]
I find that copy-n-paste works internally to the application, but that attempts to copy text in another application and paste it into a trelby document fail.  For the benefit of this ticket, I just tested copying text from a trelby document and pasting it into this text box on a git hub web form in my browser.  That also failed.  

Would be nice.

**Comment by anilgulecha** [comment]
There's an option to copy to system clipboard -- it's in the edit menu.
