### ISSUE TITLE
Request additional scene types

### ISSUE THREAD

**Issue by hesco** [oskusalerma/trelby#380]
Int. and Ext. seem to work fine, but I would like to add to those options: Archival Footage, Montage and Title card, as well.  

The script I am working on combined some limited live action with plenty of flat art, including historic documents and photographs, and perhaps some archival footage.

The reports generated by the application would be far more useful to pre-production planning were they to help me account for how much time will be spent tracking down this archival footage and shooting flat art.  

Sweet tool by the way.  Started using it only four hours ago, have knocked back the first four pages of the script (while researching appropriate photos) and am already pretty comfortable with it.  Thanks for putting this out there.

**Comment by oskusalerma** [comment]
Trelby is never going to support all the stuff needed for production purposes, so this is not going to happen.
