### ISSUE TITLE
FDX Import - OS/VO/CONT 

### ISSUE THREAD

**Issue by Mac-H** [oskusalerma/trelby#42]
Open "TestsForTelby3_CONT_VO_OS.fdx": http://dl.dropbox.com/u/800207/TempLink/TrelbyTesting/TestForTrelby3_CONT_VO_OS.fdx

Then realise you are meant to import it instead.
So import it.

Review Character Report /Dialogue Chart. 
You can see that V/O, OS .. and even CONT count as new characters.

**Comment by oskusalerma** [comment]
Issue cleanup: doubt this will ever happen, so closing.
