### ISSUE TITLE
Port to Mac OSX

### ISSUE THREAD

**Issue by anilgulecha** [oskusalerma/trelby#93]
(Note: To be taken up by a new developer, as neither of the current developers use Mac).

This should not be too difficult a task: Trelby is written using python and wxWidgets, both of which are available on the Mac. The code has some instances (listed below) when it does platform specific things. You'll have to add some Mac specific things here.

$ grep "if misc.isWindows" -i *py                 
cfgdlg.py:        if misc.isWindows:
cfgdlg.py:        if misc.isWindows:
cfgdlg.py:        if misc.isWindows:
cfgdlg.py:        if misc.isWindows:
config.py:        elif misc.isWindows:
config.py:        elif misc.isWindows:
config.py:            if misc.isWindows or (name[0] == u"/"):
finddlg.py:        if misc.isWindows:
headersdlg.py:        if misc.isWindows:
titlesdlg.py:        if misc.isWindows:
trelby.py:        if misc.isWindows:
util.py:        if misc.isWindows:

Once Trelby runs on Mac, we also need a way to package it for the platform. py2app is one (equivalent of py2exe). There may be other nsis like solutions.

**Comment by oskusalerma** [comment]
Closing, doubt this is ever going to happen.
