### ISSUE TITLE
"Keep with next" - deny page break between elements.

### ISSUE THREAD

**Issue by anilgulecha** [oskusalerma/trelby#97]
From http://messageboard.donedealpro.com/boards/showpost.php?p=781020&postcount=33

"For example, if you want a certain action graff to always be on the same page as the block of dialogue that follows it, you would put the cursor in the action block and apply "keep with next"... Then there would never be a page break between that graff and that block of dialogue. "

Basically a way to make sure the joined elements never have a pagebreak between them. MMS is seemingly the only screenwriter that provides this functionality. (Word/OpenOffice too have this). [1]

[1] http://messageboard.donedealpro.com/boards/showpost.php?p=780881&postcount=24

**Comment by oskusalerma** [comment]
Issue cleanup: doubt this will ever happen, so closing.
